### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/popsicle#184]
It looks like there's been a decent amount of development including fixes and translations since the 1.3.0 release: https://github.com/pop-os/popsicle/compare/1.3.0...master

It'd be nice to have a new release with that for Flathub users. :smile: I can open a release PR shortly, assuming `master` builds as expected.

**Comment by Scotty-Trees** [comment]
The last flatpak update for Popsicle was Nov 2020. Is it unmaintained at this point? I still use the Popsicle flatpak on Ubuntu 22.04, but just as @laniakea64 mentioned, EOL messages are now appearing, so any updates or transparency on this would be most appreciated, thank you.

**Comment by cassidyjames** [comment]
@Scotty-Trees it's maintained on the `master` branch but just seems like nobody has gone through the motions for a release here on GitHub (or updated the manifest on Flathub to point to master). I'm working on improving some Flatpak-adjacent things here with the hopes to get a fresh new release out on Flathub soon.

**Comment by Scotty-Trees** [comment]
@cassidyjames very much appreciate the update! by all means no rush, take all the time you need popsicle still works just fine, I'm just happy enough to know that it's still being taking care of as it's a wonderfully useful little app that I've enjoyed for years now. I've also always recommend it to others from time to time too since I don't think many people quite know all about it. With all that said, thanks again for the update and looking forward to seeing popsicle stick around with us.

**Comment by leviport** [comment]
Sorry this took so long, but here it is: https://github.com/pop-os/popsicle/releases/tag/1.3.1
