### ISSUE TITLE
Popsicle freezes when clicking next with image selected

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/popsicle#52]
**Distribution (run `cat /etc/os-release`):**

 aaronhoneycutt@pop-os:~/Downloads$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

aaronhoneycutt@pop-os:~/Downloads$ apt policy popsicle-gtk 
popsicle-gtk:
  Installed: 0.1.5~1530889767~18.04~2ba9db3
  Candidate: 0.1.5~1530889767~18.04~2ba9db3
  Version table:
 *** 0.1.5~1530889767~18.04~2ba9db3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

The application freezes after an image is selected and then clicking Next

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

[log.txt](https://github.com/pop-os/popsicle/files/2202520/log.txt)

**Comment by mmstick** [comment]
Does this happen even with no USB devices connected?

**Comment by ahoneybun** [comment]
Yes it does. Any logs I can help with?

**Comment by mmstick** [comment]
Do you also have issue with the CLI frontend? That would at least point to an issue with the library, instead of the GTK frontend.

**Comment by ahoneybun** [comment]
CLI frontend works I believe:

sudo popsicle -uy mini.iso /dev/sdg

**Comment by mmstick** [comment]
There's one section which loops across USB devices and attempts to get the size of each device before proceeding. Newly-connected USB devices tend to return 0 when they're still initializing, and there's a loop that will re-read the value until either the result is not 0, or 10 seconds have passed.

Although if you have no USB devices connected, then there should be no devices to check their sizes (unless something else in the system is detected as a USB device). Subsequent USB device refreshes happen asynchronously in the background, so those would never cause a hang.

There's currently no logging within the GTK frontend, so I could add that to make it easier to diagnose. I can also modify the device refresh function so that the initial device detection does not wait for devices to initialize, though there may be better means of handling a device whose size always remains 0, if that is the case.

**Comment by matt-whitaker** [comment]
@mmstick Any reason this issue is no longer being investigated? Still broken on latest Pop OS (18.10)

**Comment by mmstick** [comment]
@matt-whitaker It's been on hold due to priorities in other areas. It happens on systems with card readers. When I have time to look into this again (there's an open PR), I'm going to redo some of the GTK signal.
